/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import se.bjan.menu.*;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.addMenuItem(new TestClass("Test", "a"));
        menu.run();
    }
}
