/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import se.bjan.menu.*;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        GameManager gameManager = new GameManager();
        menu.addMenuItem(new CreateEmptyForest("Create an empty forest 🟩", "1"));
        menu.addMenuItem(new PrintForest("Print forest 🌲🌲🌲", "2"));
        menu.addMenuItem(new AddItem("Add items (🌲, 🪨) to the forest", "3"));
        menu.addMenuItem(new ListItems("List all items in the forest", "4"));
        menu.addMenuItem(new AddTreesAndRocks("Add 5🌲 and 5 🪨", "5"));
        menu.addMenuItem(new AddPlayerHunterHome("Add Player, Hunter and Home", "6"));
        menu.addMenuItem(new SaveGame("💾Save Game To File", "s"));
        menu.addMenuItem(new LoadGame("🖼️Load Game From File", "a"));
        menu.addMenuItem(new PrintAsJson("Print Game As JSON", "j"));
        menu.addMenuItem(new SaveAsJson("Save Game As JSON", "o"));
        menu.addMenuItem(new PlayGame("▶️Play Game", "p"));
        menu.addMenuItem(new Quit("❌ Quit", "q"));
        ArrayList<MenuItem> items = menu.getMenuItems();
        for(MenuItem item: items){
            item.addManager(gameManager);
        }
        menu.run();
    }
}
